### PR TITLE
assignment 25 completed

### PR DESCRIPTION
**Pull request by npauzenga**
@Enriikke so I got a little stuck here. Not on the actual method but where to put it. In the checkpoint all of our new methods (`delete_entry`, `edit_entry`, etc.) were done in `menu_controller.rb`. We don't have specs for that controller but it seems like we should be testing these methods. I watched the video to see what they did and it looks like this method ('delete_all_entries') was placed in the AddressBook model and tested there. That's cool and I followed suit but then don't a lot of these other methods belong there? I.e. it's weird to me that `delete_entry` and `delete_all_entries` are in different places.

All right Hound, you should have less to say this time...

### CODE REVIEW

**Comment by enriikke** [comment]
Hi @npauzenga you are absolutely right about the structure of the code, and I would have done the same thing you are describing. Inside `AddressBook` I would have still created a method `remove_all` that deletes all entries but shouldn't handle any user input or print out to the console. Inside `MenuController` I would have followed the same pattern as the rest of the code and created a method that had all the `p` statements, called `entries.remove_all`, and handled user input:

``` ruby
# MenuController

def main_menu
  ...
  puts "5 - ??? (completely safe)"
  ...

  case selection
  when 5
      system "clear"
      delete_all_entries
      main_menu
  ...
end

def delete_all_entries
  p "Ha! It's totally not safe!!"
  @address_book.remove_all
  p "All entries deleted!"
  puts "Press enter to return to main menu"
  gets.chomp
  system "clear"
end
```

``` ruby
# AddressBook

def remove_all
  @entries.clear
end
```

**Comment by enriikke** [comment]
P.S.: Feel free to refactor the code if you like :smiley:. The PR looks great and you can :shipit: !

**Comment by npauzenga** [comment]
@Enriikke Ok, that makes sense. Refactored this a bit. 

So the other methods (`view_entry`, `edit_entry`, `delete_entry`, `read_csv`) are in the menu controller (as opposed to the model) because they're handling logic pertaining to the view, or the presentation to the user. Is that about right?

**Comment by enriikke** [comment]
@npauzenga you are absolutely right. It's usually a good idea to separate these concerns. The methods you mentioned are part of the `MenuController` because they handle logic for the "view" (i.e. user input and output). They all use some public method of the `AddressBook` model. The good thing about this is that we can easily move our `AddressBook` model and use it in a different context because it's not coupled with logic pertaining with a very specific view/user flow. :smile:

**Pull request merged**
